INSERT INTO `LABEL` (`category`, `name`, `en_us`, `ru_ru`, `pl`) VALUES
	('account', 'haveAcc', 'Do you have account?', 'Уже есть учетная запись?', 'Czy posiadasz już konto?'),
	('account', 'password', 'Password', 'Пароль', 'Hasło	'),
	('account', 'reg_number', 'Registration number', 'УНП', 'Numer rejestracji'),
	('account', 'error_login', 'The user is already exists', 'Указанный пользователь уже существует', 'Nazwa użytkownika jest już zajęta'),
	('account', 'edit_success', 'Data is updated', 'Данные обновлены', 'Informacje zostały zaktualizowane'),
	('account', 'accept', 'I accept', 'Я принимаю', 'Akceptuję'),
	('account', 'address', 'Address', 'Адрес', 'Adres'),
	('account', 'registration', 'Registration', 'Регистрация', 'Rejestracja'),
	('account', 'phone', 'Phone', 'Телефон', 'Telefon kontaktowy'),
	('account', 'reg_number_placeholder', '0000000000', '0000000000', '0000000000'),
	('account', 'contact_us', 'Contact us', 'Напишите нам', 'Skontaktuj się z nami'),
	('account', 'message', 'Message', 'Сообщение', 'Wiadomość'),
	('account', 'termsOfUse', 'terms of use', 'Условия пользования', 'warunki umowy'),
	('account', 'login', 'Email', 'Email', 'Email'),
	('account', 'repeat_password', 'Repeat password', 'Пароль (повторить)', 'Powtórz hasło'),
	('account', 'secondStepReg', 'Second step - address information', 'Второй шаг - Информация об адресе', 'Krok drugi - informacje adresowe'),
	('account', 'edit', 'Account management', 'Управление аккаунтом', 'Zarządzenie kontem'),
	('account', 'company_name', 'Company name', 'Название компании', 'Nazwa firmy'),
	('account', 'fb_success', 'Message was sent to administrator', 'Сообщение было отправлено администратору', 'Wiadomość została wysłana do administratora strony'),
	('account', 'email', 'Your email', 'Ваша почта', 'Twój email'),
	('account', 'error_password', 'Passwords are not equal', 'Пароли не совпадают', 'Hasła się różnią'),
	('account', 'phone_placeholder', '+48000000000', '+48000000000', '+48000000000'),
	('account', 'reg_number_pattern', '^[0-9]{10}$', '^[0-9]{10}$', '^[0-9]{10}$'),
	('account', 'country', 'Country', 'Страна', 'Kraj'),
	('account', 'password_reset', 'Confirmation mail was sent', 'Письмо с подверждением выслано на вашу почту', 'Wysłano wiadomość e-mail z potwierdzeniem'),
	('account', 'send_Message', 'Send Message', 'Написать сообщение', 'Wyślij wiadomość'),
	('account', 'city', 'City', 'Город', 'Miasto'),
	('account', 'phone_pattern', '^+48[d-]{5,13}$', '^+48[d-]{5,13}$', '^+48[d-]{5,13}$'),
	('account', 'logHere', 'Log in here', 'Войти в систему', 'Zaloguj się tutaj'),
	('address', 'not_authorized', 'This isn\'t your address', 'Это не ваш адрес', 'Podany adres nie należy do użytkownika'),
	('address', 'not_default_address', 'Additional address', 'Дополнительный адрес', 'Adres dodatkowy'),
	('address', 'country', 'Country', 'Страна', 'Kraj'),
	('address', 'default_address', 'Main address', 'Основной аддрес', 'Główny adres'),
	('address', 'city', 'City', 'Город', 'Miasto'),
	('address', 'deffalt_delete_error', 'You can not remove main address', 'Невозможно удалить основной арес', 'Nie można usunąć głównego adresu'),
	('address', 'title', 'Address', 'Адрес', 'Adres'),
	('address', 'edit', 'Edit', 'Редактировать', 'Edycja'),
	('address', 'address', 'Address', 'Адрес', 'Adres'),
	('address', 'already_exists', 'Address is already exists', 'Адрес уже существует', 'Podany adres jest zajęty'),
	('build', 'number', '1', '1', '1'),
	('button', 'start_trade_now', 'Start selling now', 'Начинайте продавать', 'Natychmiastowa sprzedaż'),
	('button', 'trade', 'Trade', 'Сделка', 'Handluj'),
	('button', 'send', 'Send message', 'Отправить', 'Wyślij wiadomość'),
	('button', 'start_buy_now', 'Start buying now', 'Начинайте покупать', 'Natychmiastowy zakup'),
	('button', 'new_lot', 'New lot', 'Новый лот', 'Nowa partia'),
	('button', 'create', 'New', 'Создать', 'Nowe'),
	('button', 'addAddress', 'Add an address', 'Добавить адрес', 'Dodaj adres'),
	('button', 'ok', 'Ok', 'Ок', 'Ok'),
	('button', 'registrate', 'Register now', 'Зарегистрироваться', 'Natychmiastowa rejestracja'),
	('button', 'login', 'Login', 'Войти', 'Login'),
	('button', 'new_tender', 'New tender', 'Новый тендер', 'Nowa oferta'),
	('button', 'clear', 'Clear', 'Очистить', 'Wyczyść'),
	('button', 'finishRegistration', 'Finish registration', 'Завершить регистрацию', 'Zakończ rejestrację'),
	('button', 'back', 'Back', 'Назад', 'Wróć'),
	('button', 'continueButton', 'Continue', 'Далее', 'Kontynuuj'),
	('button', 'save', 'Save', 'Сохранить', 'Zapisz'),
	('button', 'save_start_trading', 'Start trading', 'Разместить на бирже', 'Zacznij handlować'),
	('button', 'delete', 'Delete', 'Удалить', 'Usuń'),
	('button', 'reset', 'Reset', 'Сбросить', 'Zresetuj'),
	('button', 'modify', 'Modify', 'Изменить', 'Modyfikuj'),
	('button', 'edit_categories', 'To categories', 'К категориям', 'Do kategorii'),
	('product_category', 'name', 'Name', 'Название', 'Nazwa'),
	('product_category', 'archive', 'Archived', 'Архивный', 'Zarchiwizowano'),
	('product_category', 'edit', 'Details', 'Детали', 'Szczegóły'),
	('product_category', 'category_form', 'Product category', 'Категории продукта', 'Kategorie produktów'),
	('companies', 'phone', 'Phone', 'Телефон', 'Telefon'),
	('companies', 'status', 'Status', 'Статус', 'Status'),
	('companies', 'name', 'Name', 'Имя', 'Nazwa'),
	('companies', 'reg_number', 'Registration number', 'УНП', 'Numer rejestracji'),
	('deal', 'not_authorized', 'This is not your deal', 'Это не ваша сделка', 'To nie jest twoja umowa'),
	('deal', 'reject', 'Reject', 'Отклонить', 'Odrzuć'),
	('deal', 'partnerName', 'Partner name', 'Имя партнёра', 'Nazwa strony umowy'),
	('deal', 'productName', 'Product', 'Продукт', 'Produkt'),
	('deal', 'on_approve', 'On approve', 'На подтверждении ', 'Zatwierdzone'),
	('deal', 'time', 'Deal date', 'Дата сделки', 'Data umowy'),
	('deal', 'approved', 'Approved', 'Подтверждена', 'Zatwierdzono'),
	('deal', 'partnerRegNumber', 'Partner registration number', 'УНП партнёра', 'Numer rejestracji strony umowy'),
	('deal', 'edit', 'Manage', 'Управлять', 'Zarządzaj'),
	('deal', 'on_partner_approve', 'On partner approve', 'На подтверждения у партнёра', 'Zatwierdzone przez stronę umowy'),
	('deal', 'status', 'Deal status', 'Статус сделки', 'Status umowy'),
	('deal', 'price', 'Deal price, $', 'Цена сделки, р', 'Cena przedmiotu umowy, zł'),
	('deal', 'volume', 'Deal volume, kg', 'Объём сделки, кг', 'Rozmiar przedmiotu umowy, kg'),
	('deal', 'partnerPhone', 'Partner phone', 'Телефон партнёра', 'Numer strony umowy'),
	('deal', 'partnerComment', 'Partner description', 'Комментарий партнёра', 'Opis strony umowy'),
	('deal', 'transport', 'Transport search', 'Поиск транспорта', 'Szukaj transportu'),
	('deal', 'rejected', 'Rejected', 'Отклонена', 'Odrzucono'),
	('deal', 'partnerAddress', 'Partner address', 'Адрес партнёра', 'Adres strony umowy'),
	('deal', 'approve', 'Approve', 'Подтвердить', 'Zatwierdź'),
	('index', 'about_your_trader', 'About YourTrader', 'О YourTrader', 'O platformie YourTrader'),
	('index', 'buyer', 'Buyer', 'Покупатель', 'Zamawiający'),
	('index', 'convenient_title', 'Convenient', 'Удобство', 'Dogodny'),
	('index', 'for_buyers_li3', 'Define min volume of a single delivery', 'Выберите минимальный объём 1 поставки', 'Podaj minimum logistyczne dla pojedyńczego zamówienia'),
	('index', 'for_buyers_li2', 'Define total volume you need', 'Выберите необходимы вам объём', 'Podaj całkowitą wielkość zamówienia, które chcesz złożyć'),
	('index', 'farmer', 'Supplier', 'Производитель', 'Producent rolny'),
	('index', 'trust_title', 'Trusted partners', 'Проверенные партнёры', 'Zaufani kontrahenci'),
	('index', 'for_buyers_li1', 'Define max price of the goods', 'Выберите максимальную цену на товар', 'Podaj maksymalną cenę dla produktów, które chcesz nabyć'),
	('index', 'convenient_description', 'Eysy and user friendly interface allows you to find a partner in few clicks', 'Наш простой и удобный интерейс позволит Вам находить партнёров всего в несколько кликов', 'Intuicyjny i przyjazny użytkownikowi interfejs umożliwia znalezienie kontrahenta za pomocą kilku kliknięć'),
	('index', 'sell', 'Sell', 'Продать', 'Sprzedaj'),
	('index', 'buy', 'Buy', 'Купить', 'Kup'),
	('index', 'responsive_description', 'We are thinking about you and propose you modern and user friendly interface. Where ever you are we are always with you!', 'Мы думаем о Вас и предоставляем современный и удобный интерфейс. Дома, в дороге или в поле, где бы Вы ни были мы всегда будем с Вами!', 'Zależy nam na Tobie, dlatego oferujemy nowoczesną i przyjazną w obsłudze platformę. Dokądkolwiek się udasz, będziemy tam z Tobą!'),
	('index', 'trust_description', 'We save you from unscrupulous sellers or buyers', 'Мы оберегаем Вас от недобросовестных продавцов и покупателей', 'Zapewniamy ochronę przed nieskrupulatnymi kontrahentami'),
	('index', 'phone', '739 222 391', '739 222 391', '739 222 391'),
	('index', 'description_title', 'Description', 'Описание', 'Opis'),
	('index', 'responsive_title', 'Responsive platform', 'Адаптивная платформа', 'Responsywna platforma'),
	('index', 'description', 'A quick way to find buyers or sellers of farm products', 'Быстрый способ поиска покупателей или продавцов фермерских продуктов', 'Szybki sposób na znalezienie kupujących lub sprzedających produkty rolne'),
	('index', 'speed_description', 'Our main goal is to find your trade partner as fast as possible', 'Наша главная цель - найти Вам торгового партнёра максимально быстро', 'Naszym głównym celem jest pomoc w znalezieniu kontrahenta najszybciej jak to możliwe'),
	('index', 'deal_title', 'Best prices', 'Лучшие цены', 'Najlepsze ceny'),
	('index', 'speed_title', 'Trade speed', 'Скорость продажи', 'Prędkość transakcji'),
	('index', 'for_farmers', 'For suppliers', 'Производителям', 'Dla producentów rolnych'),
	('index', 'copyright', '© 2018, YourTrader', '© 2018, YourTrader', '© 2018, YourTrader'),
	('index', 'regestrate_as_buyer', 'Or ', 'Или ', 'lub '),
	('index', 'email', 'support@yourtrader.eu', 'support@yourtrader.eu', 'support@yourtrader.eu'),
	('index', 'products', 'Products', 'Продукты', 'Produkty'),
	('index', 'phone_prefix', '+48 ', '+48 ', '+48 '),
	('index', 'for_farmers_li3', 'Define min volume of a deal', 'Выберете минимальный обём сделки', 'Podaj minimum logistyczne dla umowy'),
	('index', 'for_whom', 'For whom', 'Для кого', 'Dla kogo'),
	('index', 'for_farmers_li2', 'Define total volume of you goods', 'Выберите объём вашей продукции', 'Podaj całkowitą wielkość twojej oferty'),
	('index', 'for_farmers_li1', 'Define min price of your goods', 'Выберите минимальную цену ', 'Podaj minimalną cenę dla twoich produktów'),
	('index', 'try_it_now', 'Try it now', 'Попробуйте прямо сейчас', 'Wypróbuj '),
	('index', 'average_price', 'Average price, zł', 'Средняя цена, зл', 'Średnia cena, zł'),
	('index', 'benefits', 'Benefits', 'Преимущества', 'Zalety'),
	('index', 'for_buyers', 'For buyers', 'Покупателям', 'Dla zamawiających'),
	('index', 'deal_description', 'We are looking for your partners with best prices and minimum transport costs', 'Мы ищем партнёров для Вас с лучшими ценами и минимальными транспортными расходами', 'Pomagamy znaleźć kontrahentów z najlepszymi cenami i najniższymi kosztami transportu'),
	('index', 'regestrate_as_farmer', 'Registrate like', 'Регистрируйтесь как', 'Zarejestruj jako'),
	('index', 'requests_volume', 'Requests volume, kg', 'Объём заявок, кг', 'Wielkość zamówienia, kg'),
	('login', 'login', 'Login', 'Логин', 'Login'),
	('login', 'loginResetForm', 'Password reset', 'Сбросить пароль', 'Zresetuj hasło'),
	('login', 'password', 'Password', 'Пароль', 'Hasło'),
	('login', 'forgot', 'Forgot', 'Не помню', 'Zapomniałem'),
	('login', 'registerHere', 'Register here', 'Зарегистрируйтесь здесь', 'Zarejstruj się tutaj'),
	('login', 'dontHaveAcc', 'Don’t have an account?', 'У вас нет учетной записи?', 'Nie masz konta?'),
	('login', 'loginAgain', 'Please, login once again', 'Пожалуйста, авторизуйтесь заново', 'Proszę, spróbuj ponownie!'),
	('login', 'loginForm', 'Enter to Your Trader! ', 'Вход в Your Trader! ', 'Zaloguj do YourTrader! '),
	('lot', 'maxVolume_error', 'Maximum volume less than minimum', 'Максимальный объём меньше минимального', 'Minimum logistyczne wynosi mniej niż 1'),
	('lot', 'product_error', 'Product is not selected', 'Продукт не выбран', 'Nie wybrano produktu'),
	('lot', 'lotForm', 'Sell request', 'Заявка на продажу', 'Oferta sprzedaży'),
	('lot', 'max_volume', 'Total volume, kg', 'Максимальный объем, кг', 'Łączna ilość, kg'),
	('lot', 'creation_date', 'Creation date', 'Дата создания', 'Data wystawienia'),
	('lot', 'status', 'Status', 'Статус', 'Status'),
	('lot', 'expDate_error', 'Lot is expired', 'Лот просрочен.', 'Partia przeterminowana'),
	('lot', 'min_volume', 'Min delivery volume, kg', 'Минимальный объем, кг', 'Minimum logistyczne, kg'),
	('lot', 'exp_date', 'Valid till ', 'Активна до ', 'Obowiązuje do '),
	('lot', 'minVolume_error', 'Minimum volume less than 1', 'Минимальный объём меньше 1', 'Minimalna objętość poniżej 1'),
	('lot', 'list', 'Select from the list', 'Выберите из списка', 'Wybierz z listy'),
	('lot', 'price_error', 'Price is less than 0.01', 'Цена меньше 0.01', 'Cena wynosi mniej niż 0.01'),
	('lot', 'min_price', 'Min price, $', 'Минимальная цена, р', 'Cena minimalna, zł'),
	('lot', 'address', 'Address', 'Адрес', 'Adres'),
	('lot', 'edit', 'Edit', 'Редактировать', 'Edytuj'),
	('lot', 'product', 'Product name', 'Название продукта', 'Nazwa produktu'),
	('lot', 'description', 'Description', 'Описание ', 'Opis'),
	('navigation', 'regestration', 'Registration', 'Регистрация', 'Rejestracja'),
	('navigation', 'deals', 'Deals', 'Сделки', 'Umowy'),
	('navigation', 'account', 'Account', 'Аккаунт', 'Konto'),
	('navigation', 'version', '0.1', '0.1', '0.1'),
	('navigation', 'productsExt', 'Products admin', 'Ред. продуктов', 'Administrator produktu'),
	('navigation', 'lots', 'Selling', 'Продать', 'Sprzedaż'),
	('navigation', 'tenders', 'Buying', 'Купить', 'Zakup'),
	('navigation', 'company', 'Clients', 'Клиенты', 'Klienci'),
	('navigation', 'products', 'Products', 'Продукты', 'Produkty'),
	('navigation', 'login', 'Login', 'Войти', 'Login'),
	('navigation', 'testBG', 'Tests', 'Тесты', 'Testy'),
	('navigation', 'logout', 'Logout', 'Выйти', 'Wyloguj'),
	('product', 'details', 'Details', 'Детали', 'Szczegóły'),
	('product', 'name', 'Name', 'Наименование', 'Nazwa'),
	('product', 'delete_success', 'Product is deactivated. All lots and tenders deactivated.', 'Продукт деактивирован. Все лоты и тендеры деактивированы.', 'Produkt jest zdezaktywowany. Zdezaktywowano wszystkie zamówienia i przetagi.'),
	('product', 'delivary_price', 'Delivery price', 'Цена доставки', 'Cena dostawy'),
	('product', 'archive', 'Archived', 'Архивный', 'Zarchiwizowano'),
	('product', 'tender_volume', 'Buy requests volume, kg', 'Объём заявок на продажу, кг', 'Wolumen ofert kupna'),
	('product', 'save_success', 'Product is activated', 'Продукти активирован', 'Produkt jest aktywowany'),
	('product', 'picture', 'Picture', 'Картинка', 'Obraz'),
	('product', 'price', 'Price, $', 'Цена, $', 'Cena'),
	('product', 'lot_volume', 'Sell requests volume, kg', 'Объём заявок на покупку, кг', 'Wolumen ofert sprzedaży'),
	('product', 'edit', 'Details', 'Детали', 'Szczegóły'),
	('product', 'productForm', 'Product', 'Продукт', 'Produkt'),
	('product', 'description', 'Description', 'Описание', 'Opis'),
	('resetPassw', 'error', 'The link is out of date :(', 'Ссылка устарела:(', 'Link wygasł :('),
	('resetPassw', 'success', 'Password successfully changed and sent to your e-mail', 'Пароль успешно сменен и выслан на вашу на почту', 'Hasło zmienione i wysłane na twoją skrzynkę mailową'),
	('table', 'paginate_previous', '', '', ''),
	('table', 'decimal', ',', ',', ','),
	('table', 'infoEmpty', '', '', ''),
	('table', 'zeroRecords', 'Records are not found', 'Записи не найдены', 'Nie znaleziono'),
	('table', 'thousands', '.', '.', '.'),
	('table', 'paginate_first', 'First', 'Первая', 'Pierwszy'),
	('table', 'aria_sortDescending', ':desc', ':отсортировать по убыванию', ':desc'),
	('table', 'aria_sortAscending', ':asc', ':отсортировать по возрастанию', ':asc'),
	('table', 'search', '', '', ''),
	('table', 'processing', 'Processing...', 'Обработка...', 'Przetwarzanie...'),
	('table', 'infoFiltered', '(filtered from _MAX_ records)', '(отфильтровано из _MAX_ записей)', '(filtered from _MAX_ records)'),
	('table', 'paginate_last', 'Last', 'Последняя', 'Ostatni'),
	('table', 'searchPlaceholder', 'Search...', 'Поиск...', 'Wyszukiwanie...'),
	('table', 'emptyTable', 'No data', 'Нет доступных данных в таблице', 'Brak danych'),
	('table', 'lengthMenu', 'show _MENU_ records on page', 'показывать по _MENU_ записей', 'show _MENU_ records on page'),
	('table', 'paginate_next', '', '', ''),
	('table', 'infoPostFix', '', '', ''),
	('table', 'details', 'Details', 'Детали', 'Szczegóły'),
	('table', 'info', 'Record from _START_ to _END_ from _TOTAL_', 'Показаны записи с _START_ по _END_ из _TOTAL_', 'Record from _START_ to _END_ from _TOTAL_'),
	('table', 'loadingRecords', 'Loading...', 'Загрузка...', 'Ładowanie...'),
	('tender', 'maxVolume_error', 'Maximum volume less than minimum', 'Максимальный объём меньше минимального', 'Minimum logistyczne wynosi mniej niż 1'),
	('tender', 'product_error', 'Product is not selected', 'Продукт не выбран', 'Produkt nie został wybrany'),
	('tender', 'max_volume', 'Total volume, kg', 'Максимальный объем, кг', 'Całkowity rozmiar, kg'),
	('tender', 'creation_date', 'Creation date', 'Дата создания', 'Data utworzenia'),
	('tender', 'max_price', 'Max price, $', 'Максимальная цена, р', 'Cena maksymalna, zł'),
	('tender', 'status', 'Status', 'Статус', 'Status'),
	('tender', 'expDate_error', 'Lot is expired', 'Тендер просрочен.', 'Zamówienie wygasło'),
	('tender', 'min_volume', 'Min delivery volume, kg', 'Минимальный объем, кг', 'Minimum logistyczne, kg'),
	('tender', 'tenderForm', 'Buy request', 'Заявка на покупку', 'Oferta zakupa'),
	('tender', 'exp_date', 'Valid till', 'Активна до', 'Ważne do'),
	('tender', 'minVolume_error', 'Minimum volume less than 1', 'Минимальный объём меньше 1', 'Minimalna objętość poniżej 1'),
	('tender', 'list', 'Select from the list', 'Выберите из списка', 'Wybierz z listy'),
	('tender', 'price_error', 'Price is less than 0.01', 'Цена меньше 0.01', 'Cena wynosi mniej niż 0.01'),
	('tender', 'address', 'Address', 'Адрес', 'Adres'),
	('tender', 'edit', 'Edit', 'Редактировать', 'Edytuj'),
	('tender', 'product', 'Product name', 'Название продукта', 'Nazwa produktu'),
	('tender', 'description', 'Description', 'Описание', 'Opis'),
	('tradeOffers', 'volume', 'Volume, kg', 'Объём, кг', 'Ilość, kg'),
	('tradeOffers', 'price', 'Price, $', 'Цена, $', 'Cena, zł'),
	('tradeOffers', 'graph_title', 'requests graph', 'Гафик заявок', 'wykres ofert'),
	('user', 'not_found', 'Login or password is incorrect', 'Логин или пароль неверны', 'Login i hasło są niepoprawne'),
	('pageNames', 'lotForm', 'lot', 'Лот', 'Grupa'),
	('pageNames', 'addressForm', 'Editing an address', 'Редактирование адреса', 'Edytuj adres'),
	('pageNames', 'session', 'Your session is expired', 'Ваша сеесия закончилась', 'Sesja wygasła'),
	('pageNames', 'products', 'Product list', 'Список продуктов Биржи', 'Lista produktów'),
	('pageNames', 'myAddresses', 'Address list', 'Список адресов', 'Książka adresowa'),
	('pageNames', 'account', 'Account', 'Управление аккаунтом', 'Zarządzanie kontem'),
	('pageNames', 'checkPassw', 'Add a user', 'Добавление пользователя', 'Dodaj użytkownika'),
	('pageNames', 'registration', 'Registration', 'Регистрация', 'Rejestracja'),
	('pageNames', 'myTenders', 'Tender request list', 'Список моих тендеров', 'Lista zaproszeń do przetargów'),
	('pageNames', 'productsForAdmin', 'Product list for admin', 'Редактирование продуктов', 'Lista produktów dla administratora'),
	('pageNames', 'index', '', '', ''),
	('pageNames', 'productForm', 'Product', 'Продукт', 'Produkt'),
	('pageNames', 'deal', 'Deal details', 'Детали сделки', 'Szczegóły umowy'),
	('pageNames', 'tenderForm', 'Tender', 'Тендер', 'Przetarg'),
	('pageNames', 'login', 'Enter', 'Вход', 'Zaloguj'),
	('pageNames', 'users', 'Users', 'Пользователи', 'Użytkownicy'),
	('pageNames', 'approveLink', 'Manage transaction', 'Управление сделкой', 'Zarządzaj tranzakcją'),
	('pageNames', 'myLots', 'Sell request list', 'Список моих лотов', 'Lista ofert sprzedaży'),
	('pageNames', 'tradeOffers', 'Trade offers', 'Спрос и предложение', 'Oferty handlowe'),
	('pageNames', 'companies', 'Company list', 'Список компаний', 'Lista firm'),
	('deal', 'transporе', 'Need a transport', NULL, 'Znajdź transport'),
	('pageNames', 'myDelas', 'Deal list', NULL, 'Lista umów'),
	('navigation', 'labels', 'Labels', 'Лейблы', 'Etykiety'),
	('labels', 'category', 'Category', 'Категория', 'Kategoria'),
	('labels', 'name', 'Name', 'Имя', 'Imię'),
	('labels', 'english', 'English', 'Английский', 'Angielski'),
	('labels', 'poland', 'Poland', 'Польский', 'Polski'),
	('labels', 'russian', 'Russian', 'Русский', 'Ruski'),
	('labels', 'edit', 'Edit', 'Редактировать', 'Edytuj'),
	('labels', 'labelForm', 'Edit lable', 'Редактирование лейблы', 'Edytowanie etykiety'),
	('pageNames', 'lables', 'Lables list', 'Список лейбл', 'Lista wytwórni płytowej'),
	('pageNames', 'testbg', 'Test platform', 'Тест платформы', 'Platforma testowa'),
	('account', 'company_language', 'language', 'Язык', 'Język'),
	('deal', 'sellerAddress', 'Seller address', 'Адрес продавца', 'Adres sprzedawcy'),
	('deal', 'buyerAddrress', 'Buyer address', 'Адрес покупателя', 'Adres kupującego'),
	('pageNames', 'resetpassw', 'Password reset', 'Пароль сброшен', 'resetowanie hasła'),
	('Apple', 'name', 'Apple', 'Яблоко', 'Jabłko'),
	('Potato', 'name', 'Potato', 'Картофель', 'Ziemniaki'),
	('description', 'aboutApple', 'The fruit of apple, which is eaten fresh, serves as a raw material in cooking and for making drinks.', 'Плод яблони, который употребляется в пищу в свежем виде, служит сырьём в кулинарии и для приготовления напитков.', 'Owoce jabłka, które są świeże, służą jako surowiec do gotowania i do przyrządzania napojów.'),
	('description', 'aboutPotato', 'Potato tubers are an important food product. Fruits are poisonous, due to the content of solanine in them.', 'Клубни картофеля являются важным пищевым продуктом. Плоды ядовиты, в связи с содержанием в них соланина.', 'Bulwy ziemniaka są ważnym produktem żywnościowym. Owoce są trujące, ze względu na zawartość solaniny w nich.'),
	('lang', 'pl', 'Polski', 'Polski', 'Polski'),
	('lang', 'ru_ru', 'Русский', 'Русский', 'Русский'),
	('lang', 'en_us', 'English', 'English', 'Angielski'),
	('button', 'feedback', 'Feedback', 'Отзыв', 'Informacje zwrotne'),
	('deal', 'feedback', 'Feedback', 'Отзыв', 'Informacje zwrotne'),
	('comment', 'mark', 'Mark', 'Оценка', 'Ocena'),
	('comment', 'feedback', 'Feedback', 'Отзыв', 'Informacje zwrotne'),
	('comment', 'comment', 'Сomment', 'Комментарий', 'Skomentuj'),
	('comment', 'date', 'Date', 'Дата', 'Data'),
	('lot', 'foto', 'Foto', 'Фото', 'Zdjęcie'),
	('lot', 'distance', 'Distance, km', 'Расстояние, км', 'Odległość, km'),
	('lot', 'distance_any', 'Any', 'Любая', 'Dowolny'),
	('lot', 'distance_400', '400', '400', '400'),
	('lot', 'distance_200', '200', '200', '200'),
	('lot', 'distance_100', '100', '100', '100'),
	('lot', 'distance_40', '40', '40', '40'),
	('distance', 'distance_0', 'No delivery', 'Нет доставки', 'Brak dostawy'),
	('tender', 'distance_any', 'Any', 'Любая', 'Dowolny'),
	('tender', 'distance_400', '400', '400', '400'),
	('tender', 'distance_200', '200', '200', '200'),
	('tender', 'distance_100', '100', '100', '100'),
	('tender', 'distance_40', '40', '40', '40'),
	('tender', 'distance_0', 'No delivery', 'Нед доставки', 'Brak dostawy'),
	('tender', 'distance', 'Distance, km', 'Расстояние, км', 'Odległość, km'),
	('tender', 'packaging', 'Packaging', 'Упаковка', 'Opakowanie'),
	('tender', 'processing', 'Processing', 'Обработка', 'Przetworzenie'),
	('label', 'on_approve', 'On approve', 'На подтверждении', 'Zatwierdzone'),
	('deal', 'sellerfoto', 'Seller foto', 'Фото продавца', 'Zdjęcie sprzedawcy'),
	('account', 'fb_unsuccess', 'The letter hasn\'t been sent', 'Письмо не было отправлено', 'List nie został wysłany'),
	('lot', 'too_long_number', 'Too long number', 'Слишком длинное число', 'Za długi numer'),
	('tender', 'too_long_number', 'Too long number', 'Слишком длинное число', 'Za długi numer'),
	('lot', 'too_big', 'File too big', 'Слишком большой файл', 'Za duży rozmiar pliku'),
	('pageNames', 'myDeals', 'My deals', 'Список сделок', 'Lista umów'),
	('lot', 'category', 'Сultivar', 'Сорт', 'Odmiana'),
	('tender', 'category', 'Сultivar', 'Сорт', 'Odmiana'),
	('tender', 'category_error', 'Select a cultivar', 'Выберите сорт', 'Wybierz odmianę'),
	('index', 'login_error', 'Wrong user or password', 'Неправильное имя или пароль', 'Błędna nazwa użytkownika lub hasło'),
	('deal', 'packaging', 'Packaging', 'Упаковка', 'Opakowanie'),
	('deal', 'processing', 'Processing', 'Обработка', 'Przetworzenie'),
	('index', 'page_404', 'Page 404', 'Страница 404', 'Strona 404'),
	('index', 'message_404', 'Unfortunately the page you requested does not exist', 'К сожалению, запрошенная вами страница не существует', 'Niestety, strona, której szukasz nie istnieje'),
	('index', 'another_browser', 'Please use Google Chrome, Mozilla Firefox or Safari browsers.', 'Пожалуйста, используйте браузер Google Chrome, Mozilla Firefox или Safari', 'Proszę użyć przeglądarki Google Chrome, Mozilla Firefox lub Safari'),
	('lot', 'uploaded_foto', 'Uploaded foto', 'Загруженое фото', 'Załadowane zdjęcie'),
	('Pear', 'name', 'Pear', 'Груша', 'Gruszka'),
	('Raspberries', 'name', 'Raspberries', 'Малина', 'Malina'),
	('Strawberries', 'name', 'Strawberries', 'Клубника', 'Truskawka'),
	('Tomatoes', 'name', 'Tomatoes', 'Помидор', 'Pomidor'),
	('Carrots', 'name', 'Carrots', 'Морковь', 'Marchew'),
	('Cabbage', 'name', 'Cabbage', 'Капуста', 'Kapusta'),
	('Peppers', 'name', 'Peppers', 'Перец', 'Pieprz'),
	('Cucumber', 'name', 'Cucumber', 'Огурец', 'Ogórek'),
	('Onion', 'name', 'Onion', 'Лук', 'Cebula'),
	('Zucchini', 'name', 'Zucchini', 'Кабачок', 'Kabaczek'),
	('Pumpkin', 'name', 'Pumpkin', 'Тыква', 'Dynia'),
	('Cauliflower', 'name', 'Cauliflower', 'Цветная капуста', 'Kalafior'),
	('Parsley', 'name', 'Parsley', 'Петрушка', 'Pietruszka'),
	('Lettuce', 'name', 'Lettuce', 'Салат-латук', 'Sałata'),
	('Cherry', 'name', 'Cherry', 'Вишня', 'Wiśnia'),
	('Plum', 'name', 'Plum', 'Слива', 'Śliwa'),
	('Blueberry', 'name', 'Blueberry', 'Голубика', 'Borówka bagienna'),
	('Currant', 'name', 'Currant', 'Смородина', 'Porzeczka'),
	('Gala', 'name', 'Gala', 'Gala', 'Gala'),
	('Royal_Gala', 'name', 'Royal Gala', 'Royal Gala', 'Royal Gala'),
	('Gala_Schniga', 'name', 'Gala Schniga', 'Gala Schniga', 'Gala Schniga'),
	('Golden_Delicious_Reinders', 'name', 'Golden Delicious Reinders', 'Golden Delicious Reinders', 'Golden Delicious Reinders'),
	('Red_Jonaprince', 'name', 'Red Jonaprince', 'Red Jonaprince', 'Red Jonaprince'),
	('Red_Jonaprince_Select', 'name', 'Red Jonaprince Select', 'Red Jonaprince Select', 'Red Jonaprince Select'),
	('Jonagored', 'name', 'Jonagored', 'Jonagored', 'Jonagored'),
	('Red_Delicious', 'name', 'Red Delicious', 'Red Delicious', 'Red Delicious'),
	('Camspur', 'name', 'Camspur', 'Camspur', 'Camspur'),
	('Redchief', 'name', 'Redchief', 'Redchief', 'Redchief'),
	('RedCap', 'name', 'RedCap', 'RedCap', 'RedCap'),
	('Szampion', 'name', 'Szampion', 'Szampion', 'Szampion'),
	('Idared', 'name', 'Idared', 'Idared', 'Idared'),
	('Elise', 'name', 'Elise', 'Elise', 'Elise'),
	('Pinova', 'name', 'Pinova', 'Pinova', 'Pinova'),
	('Evelina', 'name', 'Evelina', 'Evelina', 'Evelina'),
	('Empire', 'name', 'Empire', 'Empire', 'Empire'),
	('Glostera', 'name', 'Glostera', 'Glostera', 'Glostera'),
	('Jonagolda', 'name', 'Jonagolda', 'Jonagolda', 'Jonagolda'),
	('Ligol', 'name', 'Ligol', 'Ligol', 'Ligol'),
	('Lobo', 'name', 'Lobo', 'Lobo', 'Lobo'),
	('Faworytka', 'name', 'Faworytka', 'Faworytka', 'Faworytka'),
	('Isolda', 'name', 'Isolda', 'Isolda', 'Isolda'),
	('Red_Faworytka', 'name', 'Red Faworytka', 'Red Faworytka', 'Red Faworytka'),
	('Bera_Hardy', 'name', 'Bera Hardy', 'Bera Hardy', 'Bera Hardy'),
	('Bojniczanka', 'name', 'Bojniczanka', 'Bojniczanka', 'Bojniczanka'),
	('Bonkreta_Williamsa', 'name', 'Bonkreta Williamsa', 'Bonkreta Williamsa', 'Bonkreta Williamsa'),
	('Carola', 'name', 'Carola', 'Carola', 'Carola'),
	('Concorde', 'name', 'Concorde', 'Concorde', 'Concorde'),
	('Konferencja', 'name', 'Konferencja', 'Konferencja', 'Konferencja'),
	('Lukasówka', 'name', 'Lukasówka', 'Lukasówka', 'Lukasówka'),
	('General_Leclerc', 'name', 'General Leclerc', 'General Leclerc', 'General Leclerc'),
	('Komisówka', 'name', 'Komisówka', 'Komisówka', 'Komisówka'),
	('Paryżanka', 'name', 'Paryżanka', 'Paryżanka', 'Paryżanka'),
	('Triumf_Packhama', 'name', 'Triumf Packhama', 'Triumf Packhama', 'Triumf Packhama'),
	('Agata', 'name', 'Agata', 'Agata', 'Agata'),
	('Arielle', 'name', 'Arielle', 'Arielle', 'Arielle'),
	('Denar', 'name', 'Denar', 'Denar', 'Denar'),
	('Fresco', 'name', 'Fresco', 'Fresco', 'Fresco'),
	('Impala', 'name', 'Impala', 'Impala', 'Impala'),
	('Irys', 'name', 'Irys', 'Irys', 'Irys'),
	('Lord', 'name', 'Lord', 'Lord', 'Lord'),
	('Miłek', 'name', 'Miłek', 'Miłek', 'Miłek'),
	('Orlik', 'name', 'Orlik', 'Orlik', 'Orlik'),
	('Velox', 'name', 'Velox', 'Velox', 'Velox'),
	('Gracja', 'name', 'Gracja', 'Gracja', 'Gracja'),
	('Owacja', 'name', 'Owacja', 'Owacja', 'Owacja'),
	('Irga', 'name', 'Irga', 'Irga', 'Irga'),
	('Vineta', 'name', 'Vineta', 'Vineta', 'Vineta'),
	('Asterix', 'name', 'Asterix', 'Asterix', 'Asterix'),
	('Balbina', 'name', 'Balbina', 'Balbina', 'Balbina'),
	('Bartek', 'name', 'Bartek', 'Bartek', 'Bartek'),
	('Redstar', 'name', 'Redstar', 'Redstar', 'Redstar'),
	('Roxana', 'name', 'Roxana', 'Roxana', 'Roxana'),
	('Satina', 'name', 'Satina', 'Satina', 'Satina'),
	('Tajfun', 'name', 'Tajfun', 'Tajfun', 'Tajfun'),
	('Żagiel', 'name', 'Żagiel', 'Żagiel', 'Żagiel'),
	('Syrena', 'name', 'Syrena', 'Syrena', 'Syrena'),
	('Soplica', 'name', 'Soplica', 'Soplica', 'Soplica'),
	('Zagłoba', 'name', 'Zagłoba', 'Zagłoba', 'Zagłoba'),
	('Benefis', 'name', 'Benefis', 'Benefis', 'Benefis'),
	('Beskid', 'name', 'Beskid', 'Beskid', 'Beskid'),
	('Canby', 'name', 'Canby', 'Canby', 'Canby'),
	('Laszka', 'name', 'Laszka', 'Laszka', 'Laszka'),
	('Malling_Jewel', 'name', 'Malling Jewel', 'Malling Jewel', 'Malling Jewel'),
	('Nawojka', 'name', 'Nawojka', 'Nawojka', 'Nawojka'),
	('Norna', 'name', 'Norna', 'Norna', 'Norna'),
	('Veten', 'name', 'Veten', 'Veten', 'Veten'),
	('Pokusa', 'name', 'Pokusa', 'Pokusa', 'Pokusa'),
	('Poranna_rosa', 'name', 'Poranna rosa', 'Poranna rosa', 'Poranna rosa'),
	('Dukat', 'name', 'Dukat', 'Dukat', 'Dukat'),
	('Elkat', 'name', 'Elkat', 'Elkat', 'Elkat'),
	('Honeoye', 'name', 'Honeoye', 'Honeoye', 'Honeoye'),
	('Kama', 'name', 'Kama', 'Kama', 'Kama'),
	('Korona', 'name', 'Korona', 'Korona', 'Korona'),
	('Kent', 'name', 'Kent', 'Kent', 'Kent'),
	('Onebor', 'name', 'Onebor', 'Onebor', 'Onebor'),
	('Polka', 'name', 'Polka', 'Polka', 'Polka'),
	('Selva', 'name', 'Selva', 'Selva', 'Selva'),
	('Vima_Zanta', 'name', 'Vima Zanta', 'Vima Zanta', 'Vima Zanta'),
	('Vicoda', 'name', 'Vicoda', 'Vicoda', 'Vicoda'),
	('Tresca', 'name', 'Tresca', 'Tresca', 'Tresca'),
	('Temptation', 'name', 'Temptation', 'Temptation', 'Temptation'),
	('Rainbow_Treasure_F1', 'name', 'Rainbow Treasure F1', 'Rainbow Treasure F1', 'Rainbow Treasure F1'),
	('Śliwkowe', 'name', 'Śliwkowe', 'Śliwkowe', 'Śliwkowe'),
	('Paprykowe', 'name', 'Paprykowe', 'Paprykowe', 'Paprykowe'),
	('Daktylowe', 'name', 'Daktylowe', 'Daktylowe', 'Daktylowe'),
	('Malinowe', 'name', 'Malinowe', 'Malinowe', 'Malinowe'),
	('Bawole_Serce', 'name', 'Bawole Serce', 'Bawole Serce', 'Bawole Serce'),
	('San_Marzano', 'name', 'San Marzano', 'San Marzano', 'San Marzano'),
	('Gargamele', 'name', 'Gargamele', 'Gargamele', 'Gargamele'),
	('Kapturek', 'name', 'Kapturek', 'Kapturek', 'Kapturek'),
	('Betalux', 'name', 'Betalux', 'Betalux', 'Betalux'),
	('Cytrynek_Groniasty', 'name', 'Cytrynek Groniasty', 'Cytrynek Groniasty', 'Cytrynek Groniasty'),
	('Ikarus', 'name', 'Ikarus', 'Ikarus', 'Ikarus'),
	('Faworyt', 'name', 'Faworyt', 'Faworyt', 'Faworyt'),
	('Saint_pierre', 'name', 'Saint pierre', 'Saint pierre', 'Saint pierre'),
	('Marmande', 'name', 'Marmande', 'Marmande', 'Marmande'),
	('Malinowy_Warszawski', 'name', 'Malinowy Warszawski', 'Malinowy Warszawski', 'Malinowy Warszawski'),
	('Malinowy_Kujawski', 'name', 'Malinowy Kujawski', 'Malinowy Kujawski', 'Malinowy Kujawski'),
	('Malinowy_Ożarowski', 'name', 'Malinowy Ożarowski', 'Malinowy Ożarowski', 'Malinowy Ożarowski'),
	('Apis', 'name', 'Apis', 'Apis', 'Apis'),
	('Lubań', 'name', 'Lubań', 'Lubań', 'Lubań'),
	('Zyska', 'name', 'Zyska', 'Zyska', 'Zyska'),
	('Zlatava', 'name', 'Zlatava', 'Zlatava', 'Zlatava'),
	('Moneymaker', 'name', 'Moneymaker', 'Moneymaker', 'Moneymaker'),
	('Tigerella', 'name', 'Tigerella', 'Tigerella', 'Tigerella'),
	('Brutus', 'name', 'Brutus', 'Brutus', 'Brutus'),
	('Jantar', 'name', 'Jantar', 'Jantar', 'Jantar'),
	('Hubal', 'name', 'Hubal', 'Hubal', 'Hubal'),
	('Ondraszek', 'name', 'Ondraszek', 'Ondraszek', 'Ondraszek'),
	('Szach', 'name', 'Szach', 'Szach', 'Szach'),
	('Sabała', 'name', 'Sabała', 'Sabała', 'Sabała'),
	('Poranek', 'name', 'Poranek', 'Poranek', 'Poranek'),
	('Zorza_Toruńska', 'name', 'Zorza Toruńska', 'Zorza Toruńska', 'Zorza Toruńska'),
	('Yellowstone', 'name', 'Yellowstone', 'Yellowstone', 'Yellowstone'),
	('Yellow_Pearshaped', 'name', 'Yellow Pearshaped', 'Yellow Pearshaped', 'Yellow Pearshaped'),
	('Black_cherry', 'name', 'Black cherry', 'Black cherry', 'Black cherry'),
	('Krakus', 'name', 'Krakus', 'Krakus', 'Krakus'),
	('Kmicic', 'name', 'Kmicic', 'Kmicic', 'Kmicic'),
	('Venus', 'name', 'Venus', 'Venus', 'Venus'),
	('Idyll_Aztek', 'name', 'Idyll Aztek', 'Idyll Aztek', 'Idyll Aztek'),
	('Ildi', 'name', 'Ildi', 'Ildi', 'Ildi'),
	('Płomień', 'name', 'Płomień', 'Płomień', 'Płomień'),
	('Perun', 'name', 'Perun', 'Perun', 'Perun'),
	('Pikador', 'name', 'Pikador', 'Pikador', 'Pikador'),
	('Radana', 'name', 'Radana', 'Radana', 'Radana'),
	('White_Beauty', 'name', 'White Beauty', 'White Beauty', 'White Beauty'),
	('Mirabell', 'name', 'Mirabell', 'Mirabell', 'Mirabell'),
	('Romus', 'name', 'Romus', 'Romus', 'Romus'),
	('Amsterdam', 'name', 'Amsterdam', 'Amsterdam', 'Amsterdam'),
	('Askona_F1', 'name', 'Askona F1', 'Askona F1', 'Askona F1'),
	('Berlicumer_2', 'name', 'Berlicumer 2', 'Berlicumer 2', 'Berlicumer 2'),
	('Deep_purple', 'name', 'Deep purple', 'Deep purple', 'Deep purple'),
	('Dolanka', 'name', 'Dolanka', 'Dolanka', 'Dolanka'),
	('Flakkese_2', 'name', 'Flakkese 2', 'Flakkese 2', 'Flakkese 2'),
	('Galicja_F1', 'name', 'Galicja F1', 'Galicja F1', 'Galicja F1'),
	('Kamila_F1', 'name', 'Kamila F1', 'Kamila F1', 'Kamila F1'),
	('Karlena', 'name', 'Karlena', 'Karlena', 'Karlena'),
	('Kinga_F1', 'name', 'Kinga F1', 'Kinga F1', 'Kinga F1'),
	('Kometa_F1', 'name', 'Kometa F1', 'Kometa F1', 'Kometa F1'),
	('Koral', 'name', 'Koral', 'Koral', 'Koral'),
	('Korweta_F1', 'name', 'Korweta F1', 'Korweta F1', 'Korweta F1'),
	('Krakowia_F1', 'name', 'Krakowia F1', 'Krakowia F1', 'Krakowia F1'),
	('Lenka', 'name', 'Lenka', 'Lenka', 'Lenka'),
	('Lunar_White', 'name', 'Lunar White', 'Lunar White', 'Lunar White'),
	('Nantejska', 'name', 'Nantejska', 'Nantejska', 'Nantejska'),
	('Pariser_Markt_4', 'name', 'Pariser Markt 4', 'Pariser Markt 4', 'Pariser Markt 4'),
	('Polka_F1', 'name', 'Polka F1', 'Polka F1', 'Polka F1'),
	('Rumba_F1', 'name', 'Rumba F1', 'Rumba F1', 'Rumba F1'),
	('Salsa_F1', 'name', 'Salsa F1', 'Salsa F1', 'Salsa F1'),
	('Baby_Carrots', 'name', 'Baby Carrots', 'Baby Carrots', 'Baby Carrots'),
	('Amager_Polana', 'name', 'Amager Polana', 'Amager Polana', 'Amager Polana'),
	('Benia_F1', 'name', 'Benia F1', 'Benia F1', 'Benia F1'),
	('Brunświcka', 'name', 'Brunświcka', 'Brunświcka', 'Brunświcka'),
	('Champ_F1', 'name', 'Champ F1', 'Champ F1', 'Champ F1'),
	('Ditmarska', 'name', 'Ditmarska', 'Ditmarska', 'Ditmarska'),
	('Fantazja_F1', 'name', 'Fantazja F1', 'Fantazja F1', 'Fantazja F1'),
	('Froggy_F1', 'name', 'Froggy F1', 'Froggy F1', 'Froggy F1'),
	('Headstart_F1', 'name', 'Headstart F1', 'Headstart F1', 'Headstart F1'),
	('Gaja_F1', 'name', 'Gaja F1', 'Gaja F1', 'Gaja F1'),
	('Haco', 'name', 'Haco', 'Haco', 'Haco'),
	('Irina_F1', 'name', 'Irina F1', 'Irina F1', 'Irina F1'),
	('Jowita_F1', 'name', 'Jowita F1', 'Jowita F1', 'Jowita F1'),
	('Kalina_F1', 'name', 'Kalina F1', 'Kalina F1', 'Kalina F1'),
	('Kamienna_głowa', 'name', 'Kamienna głowa', 'Kamienna głowa', 'Kamienna głowa'),
	('Karlla_F1', 'name', 'Karlla F1', 'Karlla F1', 'Karlla F1'),
	('Korund_F1', 'name', 'Korund F1', 'Korund F1', 'Korund F1'),
	('Kasta_F1', 'name', 'Kasta F1', 'Kasta F1', 'Kasta F1'),
	('Langedijker_Belwar', 'name', 'Langedijker Belwar', 'Langedijker Belwar', 'Langedijker Belwar'),
	('Langedijker_Polana', 'name', 'Langedijker Polana', 'Langedijker Polana', 'Langedijker Polana'),
	('Lotus_F1', 'name', 'Lotus F1', 'Lotus F1', 'Lotus F1'),
	('Mira_Polana_F1', 'name', 'Mira Polana F1', 'Mira Polana F1', 'Mira Polana F1'),
	('Odyssey_F1', 'name', 'Odyssey F1', 'Odyssey F1', 'Odyssey F1'),
	('Perline_F1', 'name', 'Perline F1', 'Perline F1', 'Perline F1'),
	('Performa', 'name', 'Performa', 'Performa', 'Performa'),
	('Pierwszy_zbiór', 'name', 'Pierwszy zbiór', 'Pierwszy zbiór', 'Pierwszy zbiór'),
	('Rapidasa_F1', 'name', 'Rapidasa F1', 'Rapidasa F1', 'Rapidasa F1'),
	('Replika_F1', 'name', 'Replika F1', 'Replika F1', 'Replika F1'),
	('Reserva_F1', 'name', 'Reserva F1', 'Reserva F1', 'Reserva F1'),
	('Roma_Polana', 'name', 'Roma Polana', 'Roma Polana', 'Roma Polana'),
	('Sława_Gołębiewa', 'name', 'Sława Gołębiewa', 'Sława Gołębiewa', 'Sława Gołębiewa'),
	('Starski', 'name', 'Starski', 'Starski', 'Starski'),
	('Star_Ball_F1', 'name', 'Star Ball F1', 'Star Ball F1', 'Star Ball F1'),
	('Szarada', 'name', 'Szarada', 'Szarada', 'Szarada'),
	('Późna_F1', 'name', 'Późna F1', 'Późna F1', 'Późna F1'),
	('Kujawianka', 'name', 'Kujawianka', 'Kujawianka', 'Kujawianka'),
	('Trapez', 'name', 'Trapez', 'Trapez', 'Trapez'),
	('Delphin', 'name', 'Delphin', 'Delphin', 'Delphin'),
	('Hajduczek', 'name', 'Hajduczek', 'Hajduczek', 'Hajduczek'),
	('Kier', 'name', 'Kier', 'Kier', 'Kier'),
	('Ożarowska', 'name', 'Ożarowska', 'Ożarowska', 'Ożarowska'),
	('Jupiter', 'name', 'Jupiter', 'Jupiter', 'Jupiter'),
	('Etiuda', 'name', 'Etiuda', 'Etiuda', 'Etiuda'),
	('Waga', 'name', 'Waga', 'Waga', 'Waga'),
	('Poblano', 'name', 'Poblano', 'Poblano', 'Poblano'),
	('Tabasco', 'name', 'Tabasco', 'Tabasco', 'Tabasco'),
	('Scotch_Bonnet', 'name', 'Scotch Bonnet', 'Scotch Bonnet', 'Scotch Bonnet'),
	('Cascabel', 'name', 'Cascabel', 'Cascabel', 'Cascabel'),
	('Jalapeno', 'name', 'Jalapeno', 'Jalapeno', 'Jalapeno'),
	('Chilaca', 'name', 'Chilaca', 'Chilaca', 'Chilaca'),
	('California_Wonder', 'name', 'California Wonder', 'California Wonder', 'California Wonder'),
	('Yolo_Wonder', 'name', 'Yolo Wonder', 'Yolo Wonder', 'Yolo Wonder'),
	('Ornela', 'name', 'Ornela', 'Ornela', 'Ornela'),
	('Zlata', 'name', 'Zlata', 'Zlata', 'Zlata'),
	('Dumas', 'name', 'Dumas', 'Dumas', 'Dumas'),
	('Rubinova', 'name', 'Rubinova', 'Rubinova', 'Rubinova'),
	('Marta_Polka', 'name', 'Marta Polka', 'Marta Polka', 'Marta Polka'),
	('Oda', 'name', 'Oda', 'Oda', 'Oda'),
	('Iga', 'name', 'Iga', 'Iga', 'Iga'),
	('Paradise_F1', 'name', 'Paradise F1', 'Paradise F1', 'Paradise F1'),
	('Oliwia', 'name', 'Oliwia', 'Oliwia', 'Oliwia'),
	('Mira', 'name', 'Mira', 'Mira', 'Mira'),
	('Lena', 'name', 'Lena', 'Lena', 'Lena'),
	('Afrodita', 'name', 'Afrodita', 'Afrodita', 'Afrodita'),
	('Alexander', 'name', 'Alexander', 'Alexander', 'Alexander'),
	('Balladyna', 'name', 'Balladyna', 'Balladyna', 'Balladyna'),
	('Monata', 'name', 'Monata', 'Monata', 'Monata'),
	('Kasia', 'name', 'Kasia', 'Kasia', 'Kasia'),
	('Nokturn', 'name', 'Nokturn', 'Nokturn', 'Nokturn'),
	('Hermes_F1', 'name', 'Hermes F1', 'Hermes F1', 'Hermes F1'),
	('Cezar_F1', 'name', 'Cezar F1', 'Cezar F1', 'Cezar F1'),
	('Parys_F1', 'name', 'Parys F1', 'Parys F1', 'Parys F1'),
	('Izyd_F1', 'name', 'Izyd F1', 'Izyd F1', 'Izyd F1'),
	('Polan_F1', 'name', 'Polan F1', 'Polan F1', 'Polan F1'),
	('Hela', 'name', 'Hela', 'Hela', 'Hela'),
	('Odys', 'name', 'Odys', 'Odys', 'Odys'),
	('Octopus', 'name', 'Octopus', 'Octopus', 'Octopus'),
	('Galant', 'name', 'Galant', 'Galant', 'Galant'),
	('Śremski', 'name', 'Śremski', 'Śremski', 'Śremski'),
	('White_wonder', 'name', 'White wonder', 'White wonder', 'White wonder'),
	('Partner', 'name', 'Partner', 'Partner', 'Partner'),
	('Krak', 'name', 'Krak', 'Krak', 'Krak'),
	('Anulka', 'name', 'Anulka', 'Anulka', 'Anulka'),
	('Delicius', 'name', 'Delicius', 'Delicius', 'Delicius'),
	('Ver_petit_de_Paris', 'name', 'Ver petit de Paris', 'Ver petit de Paris', 'Ver petit de Paris'),
	('Aladyn', 'name', 'Aladyn', 'Aladyn', 'Aladyn'),
	('Gregana', 'name', 'Gregana', 'Gregana', 'Gregana'),
	('Citron', 'name', 'Citron', 'Citron', 'Citron'),
	('Parys', 'name', 'Parys', 'Parys', 'Parys'),
	('Chinese_Slangen', 'name', 'Chinese Slangen', 'Chinese Slangen', 'Chinese Slangen'),
	('Dar', 'name', 'Dar', 'Dar', 'Dar'),
	('Wisconsin_SMR_58', 'name', 'Wisconsin SMR 58', 'Wisconsin SMR 58', 'Wisconsin SMR 58'),
	('Tessa', 'name', 'Tessa', 'Tessa', 'Tessa'),
	('Melonowy', 'name', 'Melonowy', 'Melonowy', 'Melonowy'),
	('Dalila', 'name', 'Dalila', 'Dalila', 'Dalila'),
	('Atlas_Pola_F1', 'name', 'Atlas Pola F1', 'Atlas Pola F1', 'Atlas Pola F1'),
	('Bolko', 'name', 'Bolko', 'Bolko', 'Bolko'),
	('Junak', 'name', 'Junak', 'Junak', 'Junak'),
	('Altaj', 'name', 'Altaj', 'Altaj', 'Altaj'),
	('Edyp', 'name', 'Edyp', 'Edyp', 'Edyp'),
	('Ibis', 'name', 'Ibis', 'Ibis', 'Ibis'),
	('Borettana', 'name', 'Borettana', 'Borettana', 'Borettana'),
	('Topolska', 'name', 'Topolska', 'Topolska', 'Topolska'),
	('Inga', 'name', 'Inga', 'Inga', 'Inga'),
	('Polanowska', 'name', 'Polanowska', 'Polanowska', 'Polanowska'),
	('Cymes', 'name', 'Cymes', 'Cymes', 'Cymes'),
	('Kristine', 'name', 'Kristine', 'Kristine', 'Kristine'),
	('Wenta', 'name', 'Wenta', 'Wenta', 'Wenta'),
	('Stuttgarter_Rieser', 'name', 'Stuttgarter Rieser', 'Stuttgarter Rieser', 'Stuttgarter Rieser'),
	('Yellow_Sweet_Spanish', 'name', 'Yellow Sweet Spanish', 'Yellow Sweet Spanish', 'Yellow Sweet Spanish'),
	('Karmen', 'name', 'Karmen', 'Karmen', 'Karmen'),
	('Supra', 'name', 'Supra', 'Supra', 'Supra'),
	('Ławica', 'name', 'Ławica', 'Ławica', 'Ławica'),
	('Octavia', 'name', 'Octavia', 'Octavia', 'Octavia'),
	('Torunianka', 'name', 'Torunianka', 'Torunianka', 'Torunianka'),
	('Sława_Ożarowa', 'name', 'Sława Ożarowa', 'Sława Ożarowa', 'Sława Ożarowa'),
	('Wiktoria_Skierniewic', 'name', 'Wiktoria Skierniewic', 'Wiktoria Skierniewic', 'Wiktoria Skierniewic'),
	('Winter_Nest', 'name', 'Winter Nest', 'Winter Nest', 'Winter Nest'),
	('Petra_F1', 'name', 'Petra F1', 'Petra F1', 'Petra F1'),
	('Alibaba', 'name', 'Alibaba', 'Alibaba', 'Alibaba'),
	('Red_Baron', 'name', 'Red Baron', 'Red Baron', 'Red Baron'),
	('Sochaczewska', 'name', 'Sochaczewska', 'Sochaczewska', 'Sochaczewska'),
	('Ailsa_Craig', 'name', 'Ailsa Craig', 'Ailsa Craig', 'Ailsa Craig'),
	('Wolska', 'name', 'Wolska', 'Wolska', 'Wolska'),
	('Szalotka', 'name', 'Szalotka', 'Szalotka', 'Szalotka'),
	('Bajkał', 'name', 'Bajkał', 'Bajkał', 'Bajkał'),
	('Vita', 'name', 'Vita', 'Vita', 'Vita'),
	('Avalon', 'name', 'Avalon', 'Avalon', 'Avalon'),
	('Tosca', 'name', 'Tosca', 'Tosca', 'Tosca'),
	('Polana', 'name', 'Polana', 'Polana', 'Polana'),
	('Agostana', 'name', 'Agostana', 'Agostana', 'Agostana'),
	('Finezja', 'name', 'Finezja', 'Finezja', 'Finezja'),
	('Aviv', 'name', 'Aviv', 'Aviv', 'Aviv'),
	('Ambition_F1', 'name', 'Ambition F1', 'Ambition F1', 'Ambition F1'),
	('Bio_Density_5', 'name', 'Bio Density 5', 'Bio Density 5', 'Bio Density 5'),
	('Tonda_Musona', 'name', 'Tonda Musona', 'Tonda Musona', 'Tonda Musona'),
	('Exhibition', 'name', 'Exhibition', 'Exhibition', 'Exhibition'),
	('Carel', 'name', 'Carel', 'Carel', 'Carel'),
	('Elody', 'name', 'Elody', 'Elody', 'Elody'),
	('Wolf', 'name', 'Wolf', 'Wolf', 'Wolf'),
	('Astra_Polka', 'name', 'Astra Polka', 'Astra Polka', 'Astra Polka'),
	('Zuboda', 'name', 'Zuboda', 'Zuboda', 'Zuboda'),
	('Złoty_Cepelin', 'name', 'Złoty Cepelin', 'Złoty Cepelin', 'Złoty Cepelin'),
	('Lajkonik', 'name', 'Lajkonik', 'Lajkonik', 'Lajkonik'),
	('Soraya', 'name', 'Soraya', 'Soraya', 'Soraya'),
	('Nimba', 'name', 'Nimba', 'Nimba', 'Nimba'),
	('Black_Beauty', 'name', 'Black Beauty', 'Black Beauty', 'Black Beauty'),
	('Tapir', 'name', 'Tapir', 'Tapir', 'Tapir'),
	('Goldena', 'name', 'Goldena', 'Goldena', 'Goldena'),
	('Atena_Polka', 'name', 'Atena Polka', 'Atena Polka', 'Atena Polka'),
	('Coucourzelle', 'name', 'Coucourzelle', 'Coucourzelle', 'Coucourzelle'),
	('Tristan_F1', 'name', 'Tristan F1', 'Tristan F1', 'Tristan F1'),
	('Nefryt_F1', 'name', 'Nefryt F1', 'Nefryt F1', 'Nefryt F1'),
	('One_Ball_F1', 'name', 'One Ball F1', 'One Ball F1', 'One Ball F1'),
	('Cora_F1', 'name', 'Cora F1', 'Cora F1', 'Cora F1'),
	('Orelia_F1', 'name', 'Orelia F1', 'Orelia F1', 'Orelia F1'),
	('Piżmowa_Butternut', 'name', 'Piżmowa Butternut', 'Piżmowa Butternut', 'Piżmowa Butternut'),
	('Pyza', 'name', 'Pyza', 'Pyza', 'Pyza'),
	('Potimarron', 'name', 'Potimarron', 'Potimarron', 'Potimarron'),
	('Ambar', 'name', 'Ambar', 'Ambar', 'Ambar'),
	('Melonowa_Żółta', 'name', 'Melonowa Żółta', 'Melonowa Żółta', 'Melonowa Żółta'),
	('Bambino', 'name', 'Bambino', 'Bambino', 'Bambino'),
	('Uchiki_Kuri', 'name', 'Uchiki Kuri', 'Uchiki Kuri', 'Uchiki Kuri'),
	('Danka_Polka', 'name', 'Danka Polka', 'Danka Polka', 'Danka Polka'),
	('Karowita_Bis', 'name', 'Karowita Bis', 'Karowita Bis', 'Karowita Bis'),
	('Junona', 'name', 'Junona', 'Junona', 'Junona'),
	('Golias', 'name', 'Golias', 'Golias', 'Golias'),
	('Waltham_Butternut', 'name', 'Waltham Butternut', 'Waltham Butternut', 'Waltham Butternut'),
	('Otylia', 'name', 'Otylia', 'Otylia', 'Otylia'),
	('Jack_O’Lantern', 'name', 'Jack O’Lantern', 'Jack O’Lantern', 'Jack O’Lantern'),
	('Justynka', 'name', 'Justynka', 'Justynka', 'Justynka'),
	('Atlantic_Giant', 'name', 'Atlantic Giant', 'Atlantic Giant', 'Atlantic Giant'),
	('Miranda', 'name', 'Miranda', 'Miranda', 'Miranda'),
	('Amazonka', 'name', 'Amazonka', 'Amazonka', 'Amazonka'),
	('Bora', 'name', 'Bora', 'Bora', 'Bora'),
	('Early_Snowball_X', 'name', 'Early Snowball X', 'Early Snowball X', 'Early Snowball X'),
	('Igloo', 'name', 'Igloo', 'Igloo', 'Igloo'),
	('Rober', 'name', 'Rober', 'Rober', 'Rober'),
	('Delta', 'name', 'Delta', 'Delta', 'Delta'),
	('Igloory', 'name', 'Igloory', 'Igloory', 'Igloory'),
	('Pionier', 'name', 'Pionier', 'Pionier', 'Pionier'),
	('Beta', 'name', 'Beta', 'Beta', 'Beta'),
	('Halblange', 'name', 'Halblange', 'Halblange', 'Halblange'),
	('Hamburska_HS', 'name', 'Hamburska HS', 'Hamburska HS', 'Hamburska HS'),
	('Kinga', 'name', 'Kinga', 'Kinga', 'Kinga'),
	('Ołomucińska', 'name', 'Ołomucińska', 'Ołomucińska', 'Ołomucińska'),
	('Cukrowa', 'name', 'Cukrowa', 'Cukrowa', 'Cukrowa'),
	('Vistula', 'name', 'Vistula', 'Vistula', 'Vistula'),
	('Sonata', 'name', 'Sonata', 'Sonata', 'Sonata'),
	('Osborne', 'name', 'Osborne', 'Osborne', 'Osborne'),
	('Eagle', 'name', 'Eagle', 'Eagle', 'Eagle'),
	('Kaśka', 'name', 'Kaśka', 'Kaśka', 'Kaśka'),
	('Hanacka', 'name', 'Hanacka', 'Hanacka', 'Hanacka'),
	('Alba', 'name', 'Alba', 'Alba', 'Alba'),
	('Berlińska', 'name', 'Berlińska', 'Berlińska', 'Berlińska'),
	('Masłowa', 'name', 'Masłowa', 'Masłowa', 'Masłowa'),
	('Mizuna', 'name', 'Mizuna', 'Mizuna', 'Mizuna'),
	('Szafir', 'name', 'Szafir', 'Szafir', 'Szafir'),
	('Michalina', 'name', 'Michalina', 'Michalina', 'Michalina'),
	('Sahim', 'name', 'Sahim', 'Sahim', 'Sahim'),
	('Maryna', 'name', 'Maryna', 'Maryna', 'Maryna'),
	('Panter', 'name', 'Panter', 'Panter', 'Panter'),
	('Goplana', 'name', 'Goplana', 'Goplana', 'Goplana'),
	('Królowa_lata', 'name', 'Królowa lata', 'Królowa lata', 'Królowa lata'),
	('Cud_Voorburgu', 'name', 'Cud Voorburgu', 'Cud Voorburgu', 'Cud Voorburgu'),
	('Rosela', 'name', 'Rosela', 'Rosela', 'Rosela'),
	('Carmina', 'name', 'Carmina', 'Carmina', 'Carmina'),
	('Maugli', 'name', 'Maugli', 'Maugli', 'Maugli'),
	('Samba', 'name', 'Samba', 'Samba', 'Samba'),
	('Great_lakes_118', 'name', 'Great lakes 118', 'Great lakes 118', 'Great lakes 118'),
	('Vanguard_75', 'name', 'Vanguard 75', 'Vanguard 75', 'Vanguard 75'),
	('Dubacek', 'name', 'Dubacek', 'Dubacek', 'Dubacek'),
	('Baby_leaf', 'name', 'Baby leaf', 'Baby leaf', 'Baby leaf'),
	('Justyna', 'name', 'Justyna', 'Justyna', 'Justyna'),
	('Paris_Island_Cos', 'name', 'Paris Island Cos', 'Paris Island Cos', 'Paris Island Cos'),
	('Crimson', 'name', 'Crimson', 'Crimson', 'Crimson'),
	('Appia', 'name', 'Appia', 'Appia', 'Appia'),
	('Bona', 'name', 'Bona', 'Bona', 'Bona'),
	('Saba', 'name', 'Saba', 'Saba', 'Saba'),
	('Ewelina', 'name', 'Ewelina', 'Ewelina', 'Ewelina'),
	('Olimp', 'name', 'Olimp', 'Olimp', 'Olimp'),
	('Larsen', 'name', 'Larsen', 'Larsen', 'Larsen'),
	('Beata', 'name', 'Beata', 'Beata', 'Beata'),
	('Cassini', 'name', 'Cassini', 'Cassini', 'Cassini'),
	('Splendor', 'name', 'Splendor', 'Splendor', 'Splendor'),
	('Atena', 'name', 'Atena', 'Atena', 'Atena'),
	('Endywia', 'name', 'Endywia', 'Endywia', 'Endywia'),
	('Debreczyn', 'name', 'Debreczyn', 'Debreczyn', 'Debreczyn'),
	('Diament', 'name', 'Diament', 'Diament', 'Diament'),
	('Dradem', 'name', 'Dradem', 'Dradem', 'Dradem'),
	('Erdi_Botermo', 'name', 'Erdi Botermo', 'Erdi Botermo', 'Erdi Botermo'),
	('Groniasta_Ujfehertoj', 'name', 'Groniasta Ujfehertoj', 'Groniasta Ujfehertoj', 'Groniasta Ujfehertoj'),
	('Kelleris_16', 'name', 'Kelleris 16', 'Kelleris 16', 'Kelleris 16'),
	('Lucyna', 'name', 'Lucyna', 'Lucyna', 'Lucyna'),
	('Łutówka', 'name', 'Łutówka', 'Łutówka', 'Łutówka'),
	('Nadwiślanki', 'name', 'Nadwiślanki', 'Nadwiślanki', 'Nadwiślanki'),
	('Nefris', 'name', 'Nefris', 'Nefris', 'Nefris'),
	('Northstar', 'name', 'Northstar', 'Northstar', 'Northstar'),
	('Pandy_103', 'name', 'Pandy 103', 'Pandy 103', 'Pandy 103'),
	('Sabina', 'name', 'Sabina', 'Sabina', 'Sabina'),
	('Książęca', 'name', 'Książęca', 'Książęca', 'Książęca'),
	('Montmorency', 'name', 'Montmorency', 'Montmorency', 'Montmorency'),
	('Naumburger', 'name', 'Naumburger', 'Naumburger', 'Naumburger'),
	('Sokówka_Nowotomyska', 'name', 'Sokówka Nowotomyska', 'Sokówka Nowotomyska', 'Sokówka Nowotomyska'),
	('Szklanka_Warki', 'name', 'Szklanka Warki', 'Szklanka Warki', 'Szklanka Warki'),
	('Tschernokorka', 'name', 'Tschernokorka', 'Tschernokorka', 'Tschernokorka'),
	('Wanda', 'name', 'Wanda', 'Wanda', 'Wanda'),
	('Wiblek', 'name', 'Wiblek', 'Wiblek', 'Wiblek'),
	('Wigor', 'name', 'Wigor', 'Wigor', 'Wigor'),
	('Wilena', 'name', 'Wilena', 'Wilena', 'Wilena'),
	('Wilga', 'name', 'Wilga', 'Wilga', 'Wilga'),
	('Winer', 'name', 'Winer', 'Winer', 'Winer'),
	('Wisok', 'name', 'Wisok', 'Wisok', 'Wisok'),
	('Wołyńska', 'name', 'Wołyńska', 'Wołyńska', 'Wołyńska'),
	('Wróble', 'name', 'Wróble', 'Wróble', 'Wróble'),
	('Amers', 'name', 'Amers', 'Amers', 'Amers'),
	('Bluefree', 'name', 'Bluefree', 'Bluefree', 'Bluefree'),
	('Brzoskwiniowa_Jerozolimka', 'name', 'Brzoskwiniowa Jerozolimka', 'Brzoskwiniowa Jerozolimka', 'Brzoskwiniowa Jerozolimka'),
	('Śliwa_cacanska', 'name', 'Śliwa cacanska', 'Śliwa cacanska', 'Śliwa cacanska'),
	('Empress', 'name', 'Empress', 'Empress', 'Empress'),
	('Herman', 'name', 'Herman', 'Herman', 'Herman'),
	('Japońska_Kometa', 'name', 'Japońska Kometa', 'Japońska Kometa', 'Japońska Kometa'),
	('Katinka', 'name', 'Katinka', 'Katinka', 'Katinka'),
	('Królowa_Wiktoria', 'name', 'Królowa Wiktoria', 'Królowa Wiktoria', 'Królowa Wiktoria'),
	('Renkloda_Althana', 'name', 'Renkloda Althana', 'Renkloda Althana', 'Renkloda Althana'),
	('Renkloda_Ulena', 'name', 'Renkloda Ulena', 'Renkloda Ulena', 'Renkloda Ulena'),
	('Renkloda_Zielona', 'name', 'Renkloda Zielona', 'Renkloda Zielona', 'Renkloda Zielona'),
	('Stanley', 'name', 'Stanley', 'Stanley', 'Stanley'),
	('Węgierka_Dąbrowicka', 'name', 'Węgierka Dąbrowicka', 'Węgierka Dąbrowicka', 'Węgierka Dąbrowicka'),
	('Węgierka_Wczesna', 'name', 'Węgierka Wczesna', 'Węgierka Wczesna', 'Węgierka Wczesna'),
	('Węgierka_Wangenheima', 'name', 'Węgierka Wangenheima', 'Węgierka Wangenheima', 'Węgierka Wangenheima'),
	('Węgierka_Zwykła', 'name', 'Węgierka Zwykła', 'Węgierka Zwykła', 'Węgierka Zwykła'),
	('Wiśniowa', 'name', 'Wiśniowa', 'Wiśniowa', 'Wiśniowa'),
	('Japońska_Dapple_Dandy', 'name', 'Japońska Dapple Dandy', 'Japońska Dapple Dandy', 'Japońska Dapple Dandy'),
	('Świdośliwa_Lamarcka', 'name', 'Świdośliwa Lamarcka', 'Świdośliwa Lamarcka', 'Świdośliwa Lamarcka'),
	('Chanticleer', 'name', 'Chanticleer', 'Chanticleer', 'Chanticleer'),
	('Earliblue', 'name', 'Earliblue', 'Earliblue', 'Earliblue'),
	('Duke', 'name', 'Duke', 'Duke', 'Duke'),
	('Spartan', 'name', 'Spartan', 'Spartan', 'Spartan'),
	('Patriot', 'name', 'Patriot', 'Patriot', 'Patriot'),
	('Bluejay', 'name', 'Bluejay', 'Bluejay', 'Bluejay'),
	('Toro', 'name', 'Toro', 'Toro', 'Toro'),
	('Bluecrop', 'name', 'Bluecrop', 'Bluecrop', 'Bluecrop'),
	('Bonus', 'name', 'Bonus', 'Bonus', 'Bonus'),
	('Sierra', 'name', 'Sierra', 'Sierra', 'Sierra'),
	('Bluegold', 'name', 'Bluegold', 'Bluegold', 'Bluegold'),
	('Chandler', 'name', 'Chandler', 'Chandler', 'Chandler'),
	('Brigitta_Blue', 'name', 'Brigitta Blue', 'Brigitta Blue', 'Brigitta Blue'),
	('Nelson', 'name', 'Nelson', 'Nelson', 'Nelson'),
	('Darrow', 'name', 'Darrow', 'Darrow', 'Darrow'),
	('Eliot', 'name', 'Eliot', 'Eliot', 'Eliot'),
	('Kazimierz_Pliszka', 'name', 'Kazimierz Pliszka', 'Kazimierz Pliszka', 'Kazimierz Pliszka'),
	('Ojebyn', 'name', 'Ojebyn', 'Ojebyn', 'Ojebyn'),
	('Titania', 'name', 'Titania', 'Titania', 'Titania'),
	('Brӧdtorp', 'name', 'Brӧdtorp', 'Brӧdtorp', 'Brӧdtorp'),
	('Ben_Alder', 'name', 'Ben Alder', 'Ben Alder', 'Ben Alder'),
	('Roodknop', 'name', 'Roodknop', 'Roodknop', 'Roodknop'),
	('Jonkheer_van_Tets', 'name', 'Jonkheer van Tets', 'Jonkheer van Tets', 'Jonkheer van Tets'),
	('Heros', 'name', 'Heros', 'Heros', 'Heros'),
	('Holenderska_Czerwona', 'name', 'Holenderska Czerwona', 'Holenderska Czerwona', 'Holenderska Czerwona'),
	('Tatran', 'name', 'Tatran', 'Tatran', 'Tatran'),
	('Biała_Jüterbog', 'name', 'Biała Jüterbog', 'Biała Jüterbog', 'Biała Jüterbog'),
	('Blanca', 'name', 'Blanca', 'Blanca', 'Blanca'),
	('index', 'error_500', '500 Internal Server Error', '500 Internal Server Error', '500 Błąd Wewnętrznego Serwera'),
	('index', 'contact_support', 'Please contact support', 'Пожалуйста, обратитесь в службу поддержки', 'Proszę skontaktuj się z administracją'),
	('index', 'by_phone', 'By phone', 'По телефону', 'Telefonicznie'),
	('index', 'or_email', 'or email', 'или email', 'lub mailowo'),
	('message', 'warning', 'Warning', 'Внимание', 'Ostrzeżenie'),
	('deal', 'categoryName', 'Сultivar', 'Сорт', 'Odmiana'),
	('index', 'index_title', 'Online platform for buying and selling farm product', 'Онлайн-площадка для покупки и продажи фермерских продуктов', 'Platforma online do sprzedaży i zakupu produktów rolnych'),
	('index', 'index_description', 'Modern online marketplace for quick buying and selling farm products • Convenient search for sellers and buyers • Try it now • YourTrader', 'Современная онлайн-площадка для быстрой покупки и продажи фермерских продуктов • Удобный поиск продавцов и покупателей • Попробуйте прямо сейчас • YourTrader', 'Nowoczesny rynek online do szybkiego kupowania i sprzedawania produktów rolnych • Wygodne wyszukiwanie dla sprzedawców i kupujących • Wypróbuj teraz • YourTrader'),
	('lot', 'category_error', 'Select a cultivar', 'Выберите сорт', NULL);