spring:
  profiles: dev
server:
  port: 8080

ses:
  support: support@yourtrader.eu
  from: info@yourtrader.eu
  accessKey: AKIAYTQSKXZOIMYMWXOE
  secretKey: 2GTO2SoRHKeulsVE8mut+uD/q+3EBZXhml3Ybl0k
  staticTo: demo@yourtrader.eu

data:
  db:
    server: localhost
    port: 7433
    database:
    user: postgres
    pass: P4ssw0rd

jwt:
  secret: jhgkg65ydfgc876vvkklkwa8
  validity:
    access: 1800
    refresh: 2592000

---
spring:
  profiles: staging

server:
  port: 8080

ses:
  support: support@yourtrader.eu
  from: info@yourtrader.eu
  accessKey: AKIAYTQSKXZOIMYMWXOE
  secretKey: 2GTO2SoRHKeulsVE8mut+uD/q+3EBZXhml3Ybl0k
  staticTo: demo@yourtrader.eu

data:
  db:
    server: stock-db-new.cbvszsmbiqz2.eu-central-1.rds.amazonaws.com
    port: 5432
    database:
    user: postgres
    pass: P4ssw0rd

jwt:
  secret: llhLKJHi986khvklkjweliu
  validity:
    access: 1800
    refresh: 2592000